### ISSUE TITLE
Make package noarch?

### ISSUE THREAD

**Issue by wolfv** [conda-forge/mlconjug3-feedstock#1]
Just because dependencies use native code doesn't mean you need native code. 
If your package is pure Python then you can make it noarch (and it will immediately be available on all platforms, including Apple Silicon).

**Comment by SekouDiaoNlp** [comment]
Thanks @wolfv , I will make the change and use `noarch`.

Cheers,

@SekouDiaoNlp.

**Comment by wolfv** [comment]
cool
